version: '3.8'

services:
  # Nginx
  proxy:
    image: nginx:latest
    container_name: onegate_proxy
    ports:
      - 80:80
    depends_on:
      - gateway
    networks:
      - http_api
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    container_name: onegate_rabbitmq
    expose:
      - 15672
    networks:
      - services
  # Postgres
  postgres:
    image: postgres:latest
    container_name: onegate_postgres
    expose:
      - 5432
    networks:
      - services
  # Api
  gateway:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_NAME: OneGate.Backend.Gateway
    container_name: onegate_gateway
    expose:
      - 80
    networks:
      - http_api
      - services
  # Account service
  account_service:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_PATH: Services
        PROJECT_NAME: OneGate.Backend.Services.AccountService
    container_name: onegate_account_service
    depends_on:
      - rabbitmq
    networks:
      - services
  # Asset service
  asset_service:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_PATH: Services
        PROJECT_NAME: OneGate.Backend.Services.AssetService
    container_name: onegate_asset_service
    depends_on:
      - rabbitmq
    networks:
      - services
  # Timeseries service
  timeseries_service:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_PATH: Services
        PROJECT_NAME: OneGate.Backend.Services.TimeseriesService
    container_name: onegate_timeseries_service
    depends_on:
      - rabbitmq
    networks:
      - services
  # Fake engine service
  fake_engine:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_PATH: Engines
        PROJECT_NAME: OneGate.Backend.Engines.FakeEngine
    container_name: onegate_fake_engine
    depends_on:
      - rabbitmq
    networks:
      - services
  fake_static_engine:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_PATH: Engines
        PROJECT_NAME: OneGate.Backend.Engines.FakeStaticEngine
    container_name: onegate_fake_static_engine
    depends_on:
      - rabbitmq
    networks:
      - services
networks:
  http_api:
  services:
      