version: '3.8'

services:
  # Nginx
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - gateway
    networks:
      - http_api
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    expose:
      - 15672
    networks:
      - services
  # Postgres
  postgres:
    image: postgres:latest
    expose:
      - 5432
    networks:
      - services
  # Api
  gateway:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_NAME: OneGate.Backend.Gateway
    expose:
      - 80
    networks:
      - http_api
      - services
  # Account service
  account_service:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_PATH: Services
        PROJECT_NAME: OneGate.Backend.Services.AccountService
    depends_on:
      - rabbitmq
    networks:
      - services
  # Asset service
  asset_service:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_PATH: Services
        PROJECT_NAME: OneGate.Backend.Services.AssetService
    depends_on:
      - rabbitmq
    networks:
      - services
  # Timeseries service
  timeseries_service:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_PATH: Services
        PROJECT_NAME: OneGate.Backend.Services.TimeseriesService
    depends_on:
      - rabbitmq
    networks:
      - services
  # Fake engine service
  fake_engine:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_PATH: Engines
        PROJECT_NAME: OneGate.Backend.Engines.FakeEngine
    depends_on:
      - rabbitmq
    networks:
      - services
  fake_static_engine:
    build:
      context: ../
      dockerfile: Backend/Dockerfile
      args:
        PROJECT_PATH: Engines
        PROJECT_NAME: OneGate.Backend.Engines.FakeStaticEngine
    depends_on:
      - rabbitmq
    networks:
      - services
networks:
  http_api:
  services:
      