// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneGate.Backend.Core.Engines.Database;

namespace OneGate.Backend.Core.Engines.Database.Migrations.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210507220055_1620424804")]
    partial class _1620424804
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("OneGate.Backend.Core.Engines.Database.Models.AssetMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<int>("EngineId")
                        .HasColumnType("integer")
                        .HasColumnName("engine_id");

                    b.Property<string>("OriginalSymbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_symbol");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "EngineId")
                        .IsUnique();

                    b.ToTable("asset_mapping");
                });
#pragma warning restore 612, 618
        }
    }
}
